version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sunnyday
  web:
    image: django_example_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_kafka_example:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
