version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sunnyday
    volumes:
      - /home/dale/django_example/postgres-data:/var/lib/postgresql/data
  zoo:
    image: zookeeper:3.6
    restart: always
    hostname: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    volumes:
      - /home/dale/django_example/docker-files/kafka/config/zookeeper.properties:/conf/zoo.cfg
      - /home/dale/django_example/zookeeper:/tmp/zookeeper
  kafka-svr:
    image: dwc-kafka
    command: /opt/kafka-2.6.0-src/bin/kafka-server-start.sh /opt/kafka-2.6.0-src/config/server.properties
    volumes:
      - /home/dale/django_example/kafka-logs:/tmp/kafka-logs
      - /home/dale/django_example/docker-files/kafka/config:/opt/kafka-2.6.0-src/config
    depends_on: 
      - zoo
  web:
    image: django_example_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/dale/django_example/docker-files/django_kafka_example:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - kafka-svr
